### ISSUE TITLE
Import data on API community

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#1]
This data will form a base layer that can show up under the various points that show various food resources. We can get this data from `tidycensus`.

**Comment by dgkeyes** [comment]
@katiejolly I've assigned you this because you're also going to bring in data on neighborhoods (see #13) so if you want to look at any relationship between neighborhood boundaries and census tracts/blocks, that would be great!

**Comment by katiejolly** [comment]
Looks like SF has developed what they call "analysis neighborhoods" based on census block boundaries! They're a similar size to census tracts but they're a little more contextually meaningful. I think they'd be great for this project so I'll go ahead with pulling that data. https://data.sfgov.org/Geographic-Locations-and-Boundaries/Analysis-Neighborhoods/p5b7-5n3h

**Comment by katiejolly** [comment]
I found this 2000 map of Asian population in SF for comparison 
![image](https://user-images.githubusercontent.com/21339677/114763990-478b0080-9d18-11eb-927a-53b7489880c3.png)

This is what my initial estimates give us
![image](https://user-images.githubusercontent.com/21339677/114764678-165f0000-9d19-11eb-8e79-c3d59fe5b1b5.png)

**Comment by dgkeyes** [comment]
Wow, that looks perfect!

**Comment by katiejolly** [comment]
Shapefile for this neighborhood % data is in the `data` folder so I'll close this issue unless we think of something else to add.
