### ISSUE TITLE
Import data on grocery stores

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#11]
The ideal here would be to use Google Places API but their terms don't allow us to do so. Can we use Open Street Map or something else to get this data? 

Also, how can we make sure we're bringing in smaller places (corner markets, convenience stores, etc) as well as large chain grocery stores?

**Comment by dgkeyes** [comment]
Also get data on convenience/corner stores

**Comment by katiejolly** [comment]
![image](https://user-images.githubusercontent.com/21339677/114649245-fbe34300-9c94-11eb-91fb-57ef4f69a361.png)

This is what the query for shop:supermarket returns from OSM. I'll look to see what other tags might be relevant as well.

**Comment by katiejolly** [comment]
Convenience stores: 
![image](https://user-images.githubusercontent.com/21339677/114650329-ee2ebd00-9c96-11eb-81af-1e4853c95bf3.png)

**Comment by dgkeyes** [comment]
Wow, awesome! Question for you: I see you use both the city + county of San Francisco. Are they different? Why use both? I'm sure there's a good reason, but I don't know what it is.

**Comment by katiejolly** [comment]
San Francisco is one of the few cities that's also a county. And I already
knew the code for getting the county boundaries, although they're
interchangeable here.

**Comment by dgkeyes** [comment]
Got it, thanks!

**Comment by katiejolly** [comment]
I found an issue with all the OSM data-- I thought that pulling points would give me the centroid, but it was actually giving all the corners of the building which is why there were so many with blank attributes. Editing all those queries now to pull the polygon but just extract the centroid!

**Comment by dgkeyes** [comment]
Super! I'm glad I have you working on this because this is already getting beyond my knowledge levels.

**Comment by katiejolly** [comment]
Closing this issue.

In the end I combined the point and polygon data, I figured out they were unique datasets. Essentially, only the largest stores had the full polygons drawn out. Others only had points.
