### ISSUE TITLE
Import neighborhood data

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#13]
List of neighborhoods:

- SOMA
- Richmond
- Sunset
- Chinatown
- Japantown
- Bayview Hunters Point
- Tenderloin
- Visitacion Valley
- Excelsior

Question is do we get demographics at the neighborhood level or using tidycensus or something like that.

**Comment by katiejolly** [comment]
I think this is covered by #1, right? I checked and all of these neighborhoods are in that dataset.

**Comment by dgkeyes** [comment]
Yeah, I think that's right. I'll go ahead and close this issue.
