### ISSUE TITLE
Import data on food pharmacies

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#15]
From email from Kathleen: 

> Food Pharmacies are a BRAND NEW thing the City of SF is launching as a part of a much larger effort to get health insurance companies to incentivize folks to eat better as a way to prevent illness. The [Food As Medicine Collaborative](https://www.hellmanfoundation.org/food-as-medicine-collaborative.html) is leading the charge. Essentially, Food Pharmacies are free food markets that are strategically placed at hospitals and clinics. Patients shop for healthy food, learn how to prepare food that supports their medical care, check their blood pressure, and receive nutrition education. [Here is a short blurb](https://www.sfproduce.org/food-pharmacy). There are only a handful of these in the City. I could easily dig them up!

**Comment by dgkeyes** [comment]
Started in https://github.com/rfortherestofus/api-food-asset-map/commit/cdfcda778f06b71390fac09637716f8995781f68

**Comment by dgkeyes** [comment]
Just need to geocode and add category variable

**Comment by grahamammal** [comment]
geocoded and added category "food pharmacy" in 4968ef10b617072c8708f0a6be5d6de3238ade24
