### ISSUE TITLE
Import data on stores that accept SNAP/WIC

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#17]
SNAP data here: https://www.ebt.ca.gov/locator/index.html#/locator.page
WIC data here: https://www.wicstorelocator.com/

We'll then need to combine this with data collected in #11 to create two categories of grocery stores: those that accept SNAP/WIC + those that don't.

**Comment by grahamammal** [comment]
imported data on snap from https://www.fns.usda.gov/snap/retailer-locator in 8e2733a169f8be434620f1dc16969ba1b70deef5

**Comment by dgkeyes** [comment]
Awesome! Where did you get the CSV from?

**Comment by grahamammal** [comment]
On the site, https://www.fns.usda.gov/snap/retailer-locator, in the paragraph below the map image they have a link to download it. I checked, it's basically the same as the data from that messy txt file, except its much cleaner and they don't include atms, just food stores

**Comment by dgkeyes** [comment]
Good eye!
