### ISSUE TITLE
Import data on farmers markets

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#19]
One data source: https://sfenvironment.org/farmers-markets-in-sf

There have to be other sources. Does OSM API have farmers markets @katiejolly?

**Comment by katiejolly** [comment]
Hm, I'm not positive. I'll check!

**Comment by dgkeyes** [comment]
Got data from website above in https://github.com/rfortherestofus/api-food-asset-map/commit/6b7060d040f27e1a52a10624cbb4695d242fa936

Let me know what you find out about OSM + farmers markets @katiejolly!

**Comment by katiejolly** [comment]
Looks like we can get "market" data, which includes farmers markets and other similar resources.

**Comment by katiejolly** [comment]
I'll post a map of those points in a bit, just cleaning the data

**Comment by katiejolly** [comment]
![image](https://user-images.githubusercontent.com/21339677/116801620-64695700-aac0-11eb-80d0-dc79430a8821.png)

We'll likely need to do some QA on this data because I think it's a pretty broad definition of "market" but it's a good starting point for now!
