### ISSUE TITLE
Develop tooltip

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#2]
I like the [tooltip design that Axios uses](https://www.axios.com/variants-tracker). 

![image](https://user-images.githubusercontent.com/13971585/114249448-7dfb0100-994f-11eb-9484-318839c582e6.png)

[Bloomberg also has nice tooltips](https://www.bloomberg.com/graphics/covid-vaccine-tracker-global-distribution/?srnd=graphics-v2). 

![image](https://user-images.githubusercontent.com/13971585/113792289-6c6ceb80-96fa-11eb-93ee-07b0510078af.png)

**Comment by katiejolly** [comment]
What sort of information are you hoping to include in the tooltip @dgkeyes ? I was thinking something like name, resource category, and neighborhood.

**Comment by dgkeyes** [comment]
Yup, that sounds great for a start! We can adjust as necessary later on.

**Comment by katiejolly** [comment]
Here's one popup option 
![image](https://user-images.githubusercontent.com/21339677/117552468-59528180-b000-11eb-89c1-9cd08aa576b8.png)

**Comment by katiejolly** [comment]
Okay! I'll keep playing around with it as well.

**Comment by katiejolly** [comment]
I started mocking up some tooltips for the neighborhoods layer as well based on the design we have for the food resources layer
![image](https://user-images.githubusercontent.com/21339677/118437630-d385a480-b697-11eb-8b53-b8f418a5a95a.png)

In places where there is no demographic data (ie parks), it'll just give the name of the area 
![image](https://user-images.githubusercontent.com/21339677/118437682-eb5d2880-b697-11eb-8181-1f6784843fda.png)

**Comment by dgkeyes** [comment]
Made some tweaks. I feel like it's close now.

**Places:** 

![image](https://user-images.githubusercontent.com/13971585/118893826-f55d7200-b8b7-11eb-9107-353d22500e03.png)

We'll need to add addresses later on and neighborhood. 

**Neighborhoods:**

![image](https://user-images.githubusercontent.com/13971585/118893853-fe4e4380-b8b7-11eb-80f5-173696d40d22.png)

I use the `percent()` function from `scales` to get nicely formatted values. I also rounded to the nearest whole number.

**Comment by dgkeyes** [comment]
Done in https://github.com/rfortherestofus/api-food-asset-map/commit/25543f679ff008558a4e2dee8e14362956a3d0fc
