### ISSUE TITLE
Clarify food resource categories

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#21]
@katiejolly I got an email from the client today. Turns out they want to use some different categories. This is the updated list they sent me:

- Providers that offer food pantries 
- Providers that offer free, prepared food/hot meals
- Food banks
- Food pharmacies 
- Drug stores
- Ethnic food markets
- Full service grocery stores/supermarkets/markets (non SNAP or WIC)
- Stores that accept SNAP/WIC (full service grocery stores, supermarkets, markets, ethnic food markets,Target, Walmart)
- Corner stores
- Fast food restaurants 
- Restaurants 
- Farmers markets
- Liquor Stores

Of these, it seems like the ones that we would potentially get from OSM are these:

- Drug stores
- Ethnic food markets
- Full service grocery stores/supermarkets/markets (non SNAP or WIC)
- Stores that accept SNAP/WIC (full service grocery stores, supermarkets, markets, ethnic food markets,Target, Walmart)
- Corner stores
- Fast food restaurants 
- Restaurants 
- Liquor Stores

Which of these categories exist on OSM that would make it possible? Do you have other thoughts about the feasibility of these categories?

**Comment by katiejolly** [comment]
The one I think would be most difficult is the ethnic food markets. I'll look into that today.

Additionally it might be a little tough to separate out stores like Target and Walmart from other department stores but I have a few ideas!

**Comment by dgkeyes** [comment]
Thanks! Let me know what you figure out.

**Comment by dgkeyes** [comment]
Sent an email to client on the SNAP/WIC issue

**Comment by katiejolly** [comment]
Liquor stores are now included on the map
