### ISSUE TITLE
Look into reverse geocoding to add addresses from coordinates

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#25]

**Comment by dgkeyes** [comment]
[Here's an explanation](https://share.getcloudapp.com/KoudkbB0). Let me know if you have any questions!

**Comment by grahamammal** [comment]
I looked into reverse geocoding, it looks like by using the Mapbox api through tidygeocoder we'll be able to get most of the addresses we're missing from osm. There are some mismatches, they're within 20 or so meters of the actual location usually. We'll need to do a paid account, it costs $5/1000 requests, and we'll probably need to do 3000 at most, so $15.

**Comment by dgkeyes** [comment]
Thanks @grahamammal. I'm happy to sign up for the Mapbox API if that makes sense. Before doing that, though, is it possible to add a buffer to the point data using `st_buffer()` (I think that's the function) and then try to join on that?

**Comment by grahamammal** [comment]
wait I might have explained things improperly, I can reverse geocode an address for every set of coordinates included using Mapbox (it's free to do it temporarily but to use the results in the final map we need to pay), but on the ones where osm has an address available, there is a mismatch maybe 30% of the time. But the street address osm returned and the street address Mapbox guessed are often for buildings that are adjacent to one another, so depending on the specifics of how the map is to be used I don't think that's a big issue? But I'm not exactly sure what adding a buffer would do?

**Comment by dgkeyes** [comment]
Wait, I think I was the one who was confused. I was thinking about this in terms of matching the SNAP/WIC stores with grocery stores etc. Please ignore! I'll let you know when I have a paid Mapbox API key for you.

**Comment by dgkeyes** [comment]
Before doing the reverse geocoding, I want to make sure the client actually cares about having addresses. I sent this to her today and I'll let you know what I hear back.

![image](https://user-images.githubusercontent.com/13971585/117735800-1680dd00-b1ab-11eb-898e-b9d622991449.png)

**Comment by dgkeyes** [comment]
Ok, still going to do the reverse geocoding. But let's wait until we have everything else set so we only have to run it once.

**Comment by grahamammal** [comment]
Finished in dfef9cef84fd0f55cd00f2fd0de661cf3759b9ce
