### ISSUE TITLE
Look into joining SNAP + all other data

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#26]

**Comment by katiejolly** [comment]
@dgkeyes Do we want to treat ethnic markets similarly? There are some duplicates because they're also listed as supermarkets or farmers markets for example. We could have a flag for `accepts_snap`, `accepts_wic` and `ethnic_market`

**Comment by katiejolly** [comment]
So far there's been mixed success with joining. One thing that's come up is that a number of gas stations accept snap/wic but we don't really have a category for them. It could go in convenience stores, but there's no guarantee that the gas stations actually have food available. We could filter just gas stations that match to snap/wic.

**Comment by dgkeyes** [comment]
I'm guessing that those are stores attached to gas stations, no? How would they show up as accepting SNAP/WIC if they didn't sell food? 

The more I think about this, the more I really feel like we need to have the SNAP/WIC as an attribute of convenience stores, drug stores, grocery stores, ethnic food markets, etc. As far as I can tell, we don't have any places in the "Full service grocery stores/supermarkets/markets (non SNAP or WIC)" category so that category will almost certainly go away. For the remaining items, it just seems like we should have a different way to filter those. Do you have thoughts @katiejolly?

**Comment by dgkeyes** [comment]
On ethnic markets, I do think they want to treat those differently. For example, a grocery store that caters primarily to the Chinese community is a very different beast than Safeway.

**Comment by katiejolly** [comment]
I think it will likely be some sort of combination. I've written a join to find the nearest feature between the two datasets (snap/wic and everything else) and it does an okay-ish job. It works as expected, but the issue is there are a number of places listed in the snap/wic data that are not in openstreetmap. I actually went through and added a few to OSM, but that isn't a great long term strategy. There were a number of places that were pretty difficult to find online at all. In order to have a high quality dataset, I do think someone should go through and manually match things up. @grahamammal you can see some of my thought process in `data-raw/try_matching_snap_wic.R`.

**Comment by katiejolly** [comment]
In the end we will likely end up supplementing the existing grocery/convenience store/etc. data with the snap/wic data for places that don't have an easy match

**Comment by katiejolly** [comment]
And re the gas station comment, the OSM data doesn't really allow us to separate out places that do and do not offer food. We could just include places that have a match in the snap/wic data. But out-of-the-box there's no differentiation between gas stations and gas stations with convenience stores that I know of (at least in the OSM data)

**Comment by grahamammal** [comment]
I agree with @katiejolly, it looks like with clever name matching, doing things like matching the big chains like cvs separately, and excluding restaurants, we could get a little over half of the snap/wic stores matched with an osm store. But as Katie said, if we want a really high-quality dataset, someone would have to go through and manually check a couple hundred.

**Comment by dgkeyes** [comment]
Ok, thanks to both of you for the input. Can one or both of you please go ahead and do everything programmatically? Once that's done, please push the data that we need manual input on to a new sheet on the Google Sheet I've created for other things in `data-raw/share-data.R`. Please just ping me when this is done and I'll email the client.

**Comment by grahamammal** [comment]
pushed a table of the closest potential match to remaining snap/wic locations in 61f9d025a24cee29f08bb1a3f2260b1a7c5483bb. The possible store info has variable suffixed with "possible match" and the snap/wic info has names suffixed with "snap_wic". I also added two columns: is_match, for them to specify if these stores match, as well as new_category, for them to put a new category for the store if there isn't a match. I only included the closest locations, as I couldn't get sf to return more locations.

**Comment by dgkeyes** [comment]
Awesome, thanks! Any chance you have a sec to jump on Zoom with me just to make sure I understand this and can share it correctly with the client?

**Comment by dgkeyes** [comment]
Actually, I'll just hang out on Zoom at [this link](https://us02web.zoom.us/j/89586131387?pwd=SDFrdjBFOWVLdzBETGZ3SS9MYkNndz09) for the next 45 minutes. If you're able to join, that would be great.

**Comment by dgkeyes** [comment]
Ok, @grahamammal, the client went through and finished her edits on the [spreadsheet](https://docs.google.com/spreadsheets/d/1AnOuJMK5HHqe3mDn0aH3Mf3JYfLS61uWnvb_kHp1xFY/edit?usp=sharing). She sent the following notes: 

> 1. Some places were closed, so I used the strikethrough to denote this
> 2. I noted a lot of duplicates and highlighted them in grey
> 3. There were a few shops on the WIC list that were cafes or things other than our typologies. I noted these as "--" in the "new category" column; so let's delete them from the map
> 4. On the map, can the supermarket category be listed as "Supermarkets/Grocery Stores"?
> 5. On the map, can we list corner stores as "Corner Stores/Convenience Stores"?

Can you please go ahead and incorporate the changes? Sorry, this is going to be some manual work. 

Can you also please update the names per the client's request? 

Please let me know when this is all done so we can then reverse geocode everything that's missing an address (#25). Thanks!

**Comment by grahamammal** [comment]
I did the final join in 2ec3e9fd80a80d83e371d87b52f0f7a6e7e2100a and updated the category names in c1aac2a8f44bc0c10d7bb953a0577ca3c87d875d. I saved this new dataset as final_snap_wic_dataset.rds

 I can start and probably finish the reverse geocoding tomorrow

This should also have mostly dealt with duplicates, but there might still be more that I just can't catch

**Comment by dgkeyes** [comment]
Super, thanks so much, Ellen! 

Please let me know when you have the reverse geocoding done. 

On the duplicates, is there a way that we could have the client manually check our data and flag duplicates?

**Comment by grahamammal** [comment]
I think the last way for us to catch them would be by mapping the data and just looking for them? It looks like almost all of the remaining duplicates are international grocery stores, so I think somewhere along the line something got messed up when we kept changing things for them. I just finished reverse geocoding in dfef9cef84fd0f55cd00f2fd0de661cf3759b9ce, (and removed a couple dupes I found), so if we map this data for them maybe they would be able to find any last duplicates?

**Comment by dgkeyes** [comment]
Thanks! On duplicates we can definitely get the clients to help. Can we also use st_nearest_feature() or something like that to find the closest places and then manually look at the ones that are, say, less than 10 meters apart?

**Comment by dgkeyes** [comment]
@grahamammal if there's any chance we can get this to the client today so they can look at it tomorrow and we can launch on Wednesday, that would be great. Thanks!

**Comment by grahamammal** [comment]
@dgkeyes sorry for taking so long, added a sheet called Potential Duplicates in 297150b4d9358e9aa6eeb19a8530f1bea268740f. It includes all locations that are within 15 meters of each other, styled basically the same as the snap/wic matching sheet.

**Comment by dgkeyes** [comment]
Perfect, thanks so much!

**Comment by dgkeyes** [comment]
I just took a look. One thing I'm seeing is that there are a bunch of places that we can easily rule out as duplicates because the names are so different. I tried to add a column for string distance (i.e. number of different characters in the name of place A + place B) but couldn't figure it out. See https://github.com/rfortherestofus/api-food-asset-map/commit/052211080dc34998096377ab61a4c6cde0d0795a. Would adding a string distance column allow us to easily filter some places out so we can have the client look at a smaller number of places, do you think?

**Comment by grahamammal** [comment]
This mutate will do what you wanted in 0522110:
`mutate(string_distance = map2_dbl(name_location_1, name_location_2,  
                                    ~stringdist(a = .x,
                                                 b = .y,
                                                 method = "jw")))`

I'm not super familiar with string distance, what do you think a good cutoff would be?

**Comment by dgkeyes** [comment]
Ok, thanks. I ran that and just eyeballed the data. There are actually only a few that are obviously duplicates. I'll just share what's on the Google Sheet from before and have the client deal with it.

**Comment by dgkeyes** [comment]
Ok @grahamammal the client has identified duplicates. If you can please remove those and let me know when it's done, that would be great! Also, can you please confirm that #27 is taken care of and all of the data is final? Thanks!

**Comment by grahamammal** [comment]
I removed the final duplicates in 70fd752ea9350b352314233b9bfd962c0c4d8c93. For #27 encodings look correct on my computer. I think this is our final dataset! We also need to rerun our icon summaries, should I do that now or does that happen during the website render process?

**Comment by dgkeyes** [comment]
Super, thanks! What is the final RDS file called? I'm wondering if we need to rewrite code to import the correct data to generate the maps + to make the icon summaries. If you could do that and rerun the icon summaries, that would be great!

**Comment by grahamammal** [comment]
It's called `final_dataset_no_dupes.rds`. I can get on that right now. Do you know the command we've been using to build the site so I can test it before I push?

**Comment by dgkeyes** [comment]
Take a look at https://github.com/rfortherestofus/api-food-asset-map/blob/main/R/render.R. You can comment out line 14, which builds TailwindCSS code. I'm not sure if that will work for you since you probably don't have Tailwind installed but it shouldn't matter for testing.

**Comment by grahamammal** [comment]
I updated the files for the new data in 4fcaee81d87f40d33b78af43485afaee789ebded. I didn't push my rebuild of the website, figured I'd let you do that with Tailwind, but everything looks correct when I looked through it locally

**Comment by dgkeyes** [comment]
Awesome thanks so much! I'll test it out and let you know if everything works on my end.

**Comment by dgkeyes** [comment]
Ok, it works! I think we're all set. I'm working with the client to get the site up on their domain. Will let you know when that happens. Thanks again!
