### ISSUE TITLE
Look into encoding on names (e.g. special characters etc)

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#27]

**Comment by dgkeyes** [comment]
[Made a video explanation](https://share.getcloudapp.com/jkuLpwZx). @katiejolly the data actually looks fine on my end. I wonder if something weird is going on on your end.

**Comment by grahamammal** [comment]
so it does look like it's an encoding issue, where windows assumes its the wrong encoding. Here's a function to fix it:

```
fix_encoding <- function(dataset) {
  dataset_names <- names(dataset)[which(names(dataset) != "geometry")]

  for(col in dataset_names) {
    Encoding(dataset[[col]]) <- "UTF-8"
  }
  dataset
}
```

I'll apply this to all of the datasets after I get them all reverse geocoded and standardized

**Comment by dgkeyes** [comment]
Sounds good, thanks!

**Comment by dgkeyes** [comment]
I think this is taken care of, but please let me know if otherwise @grahamammal and @katiejolly.
