### ISSUE TITLE
Come up with color scheme

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#3]
I'm not sure whose branding this project should reflect. We'll need to inquire.

**Comment by dgkeyes** [comment]
Again, they don't really have branding guidelines so we can do whatever we want. Let's incorporate the red from their logo somehow, but beyond that we can make it up.

![image](https://user-images.githubusercontent.com/13971585/114943136-5f3ab580-9dfa-11eb-925d-99542a715015.png)

**Comment by katiejolly** [comment]
```
dark_red <- "#AD1D32"
light_red <- "#E00052"
off_white <- "#FDFAF9"
gray <- "#806E6E"
```

**Comment by katiejolly** [comment]
This is just pulled from the image above, we can see how things are looking and make any changes we need to

**Comment by dgkeyes** [comment]
Closing this as we've basically incorporated it into the code.
