### ISSUE TITLE
Add ethnic food markets

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#31]
I explained to the client the issue about ethnic food markets being interspersed with other data and here's what she responded: 

> Hmmm....I was really hoping we wouldn't have to collapse the 2 categories. As you can imagine, API Council is very interested in distinguishing between an Asian Food Market vs Kroger (for example). Is there another keyword/search term we could try? Maybe "speciality market" or "international grocers" or "ethnic grocery store," or  "global food market"? 

@katiejolly can you please look to see if there's any OSM category we could use like the ones she suggests so I can let her know? Thanks!

**Comment by katiejolly** [comment]
It looks like a few of them actually do have a *cuisine *tag. Off the top
of my head I'm not sure how to just pull anything with that tag (rather
than a specific value), but I will look into it today!

**Comment by dgkeyes** [comment]
Let me know what you find out @katiejolly!

I think the best approach generally for dealing with ethnic markets is going to be to have us consolidate all data and then put it in a Google Sheet. The client may go through manually and tag places that we should treat as ethnic markets. Just FYI (cc: @grahamammal).

**Comment by katiejolly** [comment]
Here's one option:

I can search for specific cuisines (I've tested Japanese, and we could make a list) and then join that dataset to our more general food resource dataset on the OSM ID. Then it would add a field for cuisine (NA if not listed). How does that sound? Most of the  places labeled with cuisine are restaurants, but I think we might get lucky with a few markets or supermarkets. For example there were 0 Japanese markets and 1 Japanese supermarket.

**Comment by katiejolly** [comment]
Okay so there aren't that many "markets" that are marked with the cuisine tag. Instead I've been compiling a list based on some online sources (https://www.sfgate.com/food/article/The-Bay-Area-s-best-international-markets-11157138.php#taboola-9, https://ss-biggie.livejournal.com/42231.html) and then getting coordinates from google maps 

I've got these so far 
![image](https://user-images.githubusercontent.com/21339677/117555003-4182f980-b010-11eb-84a5-55590c7b49b9.png)

**Comment by katiejolly** [comment]
![image](https://user-images.githubusercontent.com/21339677/117555462-3af68100-b014-11eb-99c9-7ab327512242.png)

**Comment by dgkeyes** [comment]
Ok, thanks. I can also ask the client to look through our list and tag some places that are ethnic markets by their definition.

**Comment by dgkeyes** [comment]
FYI, sent this to client today:

![image](https://user-images.githubusercontent.com/13971585/117735759-f81ae180-b1aa-11eb-9a85-2c80f4e1f235.png)

**Comment by dgkeyes** [comment]
Ok, the client made edits on [this Google Sheet](https://docs.google.com/spreadsheets/d/1AnOuJMK5HHqe3mDn0aH3Mf3JYfLS61uWnvb_kHp1xFY/edit#gid=26206645). It looks like they put an x for those we should count as ethnic food markets and also put CLOSED on some stores. 

@grahamammal can you please incorporate this? Obviously, we should just remove the places they tagged as closed. 

One other thing: the client requested we change "ethnic food market" to "international grocery store". Can you please make that change as well? Thanks!

**Comment by grahamammal** [comment]
Sure thing, I'll get started on this right now

**Comment by grahamammal** [comment]
Added international_grocery_store column as a logical variable in 3af833c455beb4f89e06c5fc013a8930bd044583, and removed the 20 closed locations
