### ISSUE TITLE
Add food banks

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#32]
I got this directly from the client

<span >Luckily (or unluckily) there are only a few true food banks in SF; most are pantries. Below are the "big" food hubs.</span><br >

name | street_address | city | state | zip_code
-- | -- | -- | -- | --
San Francisco-Marin Food Bank | 900 Pennsylvania Ave | San Francisco | CA | 94107
Food Runners | 2579 Washington St | San Francisco | CA | 94115
Free the Need | 827 Joost Ave | San Francisco | CA | 94127
San Francisco-Marin Food Bank-Illinois Warehouse | 1050 Marin St | San Francisco | CA | 94124

@grahamammal can you please geocode and add these as an RDS object?

**Comment by grahamammal** [comment]
Added and geocoded in e7b62ed11449beac80ad0c3d928095d5e5cfecd0
