### ISSUE TITLE
Explore making bivariate map

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#35]
Could do something that shows % of API folks in neighborhood and number of food resources. Inspiration: [McKinsey COVID vaccine distribution map](https://covid-tracker.mckinsey.com/vaccination-map).

![image](https://user-images.githubusercontent.com/13971585/117374299-c55aab80-ae81-11eb-9f04-28eec342f4a3.png)

**Comment by katiejolly** [comment]
Bivariate maps are pretty difficult to do with Leaflet and my level of Javascript, but I will look into it!

**Comment by dgkeyes** [comment]
Oh, sorry, didn't mean to imply I was going to ask you to do this! I was just putting this as an idea to explore. If anything, I would use the `biscale` package to create static ggplot-based maps.

**Comment by dgkeyes** [comment]
[Or possibly use ggiraph to make a basic interactive map](https://davidgohel.github.io/ggiraph/reference/geom_sf_interactive.html).

**Comment by dgkeyes** [comment]
I like the idea of this, but given the timeframe I don't think we'll be able to do this. I'm closing the issue.
