### ISSUE TITLE
Prototype leaflet map

### ISSUE THREAD

**Issue by katiejolly** [rfortherestofus/api-food-asset-map#36]

**Comment by katiejolly** [comment]
@dgkeyes Here are some screenshots of the _very drafty_ prototype! 
![image](https://user-images.githubusercontent.com/21339677/117379877-53885f00-ae8d-11eb-9e53-c423c0c3ffad.png)

![image](https://user-images.githubusercontent.com/21339677/117379900-6307a800-ae8d-11eb-8359-2eb291dd01b0.png)

![image](https://user-images.githubusercontent.com/21339677/117379944-80d50d00-ae8d-11eb-9be3-4ef1c0d7fd93.png)

All the code you need to reproduce this is in R/map.R if you want to take some other screenshots to share with the client.

**Comment by dgkeyes** [comment]
Super, thanks! I'll share this with them tomorrow.

**Comment by dgkeyes** [comment]
Thanks again for putting this together @katiejolly! I've taken your work that was in the R folder and moved it all into an RMarkdown document (index.Rmd). [Here's a quick explanation](https://share.rfor.us/llu5bdYw). Let's work in this Rmd file from now on for the main map. We'll also build individual pages for neighborhoods. We can work on that later on.

**Comment by katiejolly** [comment]
Looks great, thanks!

**Comment by dgkeyes** [comment]
Is it possible to separate out the neighborhood demographics from the other filters? Like, could we put a toggle or something like that to show/hide the demographics on the bottom left?

**Comment by katiejolly** [comment]
Hm, off the top of my head I don't know but I will look into that!

**Comment by katiejolly** [comment]
With your helpful suggestion to use crosstalk, here's a prototype of the demographics data separated out 

![image](https://user-images.githubusercontent.com/21339677/118410656-66492380-b645-11eb-878e-7f992870dad9.png)
![image](https://user-images.githubusercontent.com/21339677/118410669-76610300-b645-11eb-8ae2-422a9c9ae506.png)

**Comment by dgkeyes** [comment]
That's looking good! For neighborhood demographics, can we just make it a single checkbox that says:

Show demographics [] 

When it's unchecked, demographics would be hidden and vice versa.

**Comment by katiejolly** [comment]
Yep!

**Comment by katiejolly** [comment]
The downside of the crosstalk approach is that is does not support clustering markets https://github.com/rstudio/leaflet/issues/478

**Comment by dgkeyes** [comment]
Hmm, that's too bad. Let me know if adding two filtering mechanisms (one for category, one for showing/hiding demographics) just using leaflet seems feasible. If not, we'll just have to figure out which option seems less bad.

**Comment by katiejolly** [comment]
I've tried a few ideas but so far it doesn't seem possible to have two separate filters with just leaflet, at least not without Javascript that I wouldn't be able to write. 

A third option would be using css to differentiate the label if we do go the "plain leaflet" route. Here's an example of using the icons in the group name: https://stackoverflow.com/questions/47227557/add-icons-to-layer-control-in-leaflet-r. We could do something similar here and include some sort of icon or other styling that makes the demographics layer control look noticeably different.

**Comment by katiejolly** [comment]
Another tricky thing about crosstalk is that it's not immediately clear to me how to toggle the legend for the demographics layer, although I could probably think of something. All-in-all I think I'm leaning slightly towards the leaflet (not crosstalk) side.

**Comment by dgkeyes** [comment]
Ok please go with whatever you think is best and manageable in the time frame!

**Comment by katiejolly** [comment]
Alright not sure why there's a huge space around the horizontal line but I'll edit the CSS for that. Is this closer to what you had in mind?

![image](https://user-images.githubusercontent.com/21339677/118418239-7cb6a580-b66c-11eb-875d-6ab24efe072e.png)
![image](https://user-images.githubusercontent.com/21339677/118418243-86d8a400-b66c-11eb-8745-22a8c74fe4c8.png)

(Includes the clustering as well. The counts of points auto-updates when a user toggles categories)

**Comment by dgkeyes** [comment]
Yup, this looks great! Let's go with this as opposed to crosstalk.

**Comment by dgkeyes** [comment]
I'm going to close this issue and create a few separate issues around styling the map
