### ISSUE TITLE
Decide on font(s)

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#4]
Will need to use these fonts in the distill template as well as tooltips etc on the map

**Comment by katiejolly** [comment]
fwiw the body test on the API council website is Catamaran https://fonts.google.com/specimen/Catamaran

**Comment by dgkeyes** [comment]
Cool, thanks. They're going to send a branding guide soon.

**Comment by dgkeyes** [comment]
Ok, turns out the "branding guide" is really just a logo lol. So we can use whatever fonts we want. Let's start with Catamaran and see if it works. 

![image](https://user-images.githubusercontent.com/13971585/114942963-2ac6f980-9dfa-11eb-8f65-ce63962976d5.png)
