### ISSUE TITLE
Merge all data into one giant data frame

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#40]
See #39

**Comment by grahamammal** [comment]
Completed in f77a0e785575956082491a980640f01547fa9b1a

I used the following for the mapping between file and category:

`tribble(~name, ~category,
        "bay_area_211", "Offers Free, Prepared Food or Hot Meals",
        "convenience_stores_osm", "Corner Store",
        "drugstores_osm", "Drug Store",
        "farmers_markets", "Farmers Market",
        "fast_food_osm", "Fast Food Restaurant",
        "food_banks", "Food Bank",
        "food_pantries", "Food Pantry",
        "food_pharmacies", "Food Pharmacy",
        "pop_up_pantries", "Food Pantry",
        "prepared_food", "Offers Free, Prepared Food or Hot Meals",
        "restaurants_osm", "Restaurant",
        "snap_stores", "Accepts SNAP",
        "supermarkets", "Supermarket",
        "wic_stores", "Accepts WIC")
`

Let me know if I should change any. I also didn't include the market_osm dataset, I couldn't really figure out what it contained?

**Comment by katiejolly** [comment]
The markets data was a first pass at farmers markets from the OSM data, but your dataset is much higher quality! So don’t worry about that one.

**Comment by katiejolly** [comment]
Labels look great @grahamammal ! 
![image](https://user-images.githubusercontent.com/21339677/117553015-dc290b80-b003-11eb-93da-d44471ddb038.png)

**Comment by katiejolly** [comment]
@grahamammal I added liquor store data into the full dataset, I'd previously missed that category

**Comment by dgkeyes** [comment]
This looks great! I made a few small tweaks to the labels in https://github.com/rfortherestofus/api-food-asset-map/commit/4ff9d9a490e9d79e7271e409333eff378e7606f4

**Comment by katiejolly** [comment]
I'm thinking the plural labels are good for the menu and singular labels for the tooltip? I'm forgetting the name but there's an R package that will make all the labels singular so we don't need to go back and do that ourselves.

**Comment by dgkeyes** [comment]
That's a great point! If you find that package, let me know. We can also just create two columns manually, one for each purpose.

**Comment by katiejolly** [comment]
Found it! https://cran.r-project.org/web/packages/pluralize/pluralize.pdf 
None of these labels are particularly difficult or obscure so I'm guessing this will be a good solution

**Comment by katiejolly** [comment]
![image](https://user-images.githubusercontent.com/21339677/117919212-722d9200-b2a1-11eb-8ace-71256fc462ae.png)

**Comment by dgkeyes** [comment]
That works!

**Comment by dgkeyes** [comment]
@grahamammal here are the final categories. I started to update the code in make-full-dataset.R but was worried I might mess something up. Do you mind finalizing things there?

- Corner Stores
- Drug Stores
- Ethnic Markets
- Farmers Markets
- Food Banks/Pantries (merged food banks and food pantries)
- Food Pharmacies
- Free Prepared Food or Hot Meals
- Liquor Stores
- Restaurants
- Restaurants (Fast Food)
- Supermarkets

Also, since accepts SNAP/WIC is now a separate variable, please go ahead and create that variable and do the merging we are able to (see #26). Please let me know when that's all set so I can get the client to help with manual matching. Thanks!

**Comment by grahamammal** [comment]
Do we still want the Ethnic Markets category if we have a separate variable for international markets? I can match the stores with that category to another category if we want

**Comment by dgkeyes** [comment]
First of all, I think I had a typo above (forgot to change Ethnic Markets to International Grocery Stores). I fixed that now. 

We no longer need ethnic markets as a category/variable. With the international_grocery_store variable, we should make any store that has that get the category "International Grocery Stores". We can then drop the international_grocery_store variable. 

Let me know if this makes sense after I did my best to confuse you!

**Comment by grahamammal** [comment]
Okay I think I got that sorted out in 79a1eb94b76506a0e9657fb0b1bbc38b2487c412, but you should check to make sure it looks correct

**Comment by grahamammal** [comment]
One thing I forgot to mention, I'm leaving in the snap/wic category in that dataset, so I can use it in the file for matching up with snap/wic info

**Comment by dgkeyes** [comment]
Great, looks good to me! Onward to doing the programatic matching we can do in #26! I'll close this issue and we can discuss anything else that comes up in #26.
