### ISSUE TITLE
Make static maps for home page

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#41]
One map per neighborhood. Started code in https://github.com/rfortherestofus/api-food-asset-map/commit/517b943315961733673533ac30c6e82f73faac48

**Comment by dgkeyes** [comment]
Like this but for neighborhoods:

![image](https://user-images.githubusercontent.com/13971585/117914001-4c02f480-b297-11eb-9eaa-ad5685c3ba5b.png)

**Comment by dgkeyes** [comment]
@grahamammal do you want to take a stab at this? [I made a short video to show what I'm looking for](https://share.rfor.us/04uAjZNZ). I also very quickly started the code in `static-maps.R`.

**Comment by grahamammal** [comment]
@dgkeyes I think the screen recording got messed up, I can't see a mod up of the website on it. But I can make maps like those above no problem

**Comment by dgkeyes** [comment]
Thanks! Would you also please do me a favor and try adding a drop shadow behind each one like in [this tweet](https://twitter.com/kyle_e_walker/status/1392856010017185793?s=09)? 

![image](https://user-images.githubusercontent.com/13971585/118154967-8d48f080-b3cc-11eb-8cfa-ebd7962d45c8.png)

This uses the `ggfx` package, which I haven't used yet, but would love to see how it looks.

**Comment by dgkeyes** [comment]
Actually, if you haven't started this yet @grahamammal, please hold off. I have a different idea for how to do this.

**Comment by grahamammal** [comment]
@dgkeyes Do you want me to do any work on this or did you get it sorted out?

**Comment by dgkeyes** [comment]
Sorry, you can hold off on this! I wrote the code, but just need to figure out how to handle the neighborhoods, as discussed in #55.

**Comment by dgkeyes** [comment]
All set
