### ISSUE TITLE
Build out icon + number summaries

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#44]
We can work on this after I come up with icons to use (see #30). 
 
![image](https://user-images.githubusercontent.com/13971585/118057158-254cc880-b340-11eb-8fba-2c59f1321d45.png)

**Comment by dgkeyes** [comment]
@grahamammal I assigned you this now that I've added icons in #45. I'm hoping you might be up for helping on this issue. I want to make little summaries that show the total number of each type of food resource. 

![image](https://user-images.githubusercontent.com/13971585/118412356-5d108480-b64e-11eb-8d03-b73bd903fda5.png)

[I recorded a short video to explain my thinking](https://share.rfor.us/p9ubq96g). Let me know if you have any questions. Thanks!

**Comment by dgkeyes** [comment]
Actually, if you haven't started this yet @grahamammal, please hold off. I have a different idea for how to do this.

**Comment by dgkeyes** [comment]
Ok, never mind. My approach isn't working so let's have you work on this @grahamammal per the original plan. Thanks!

**Comment by grahamammal** [comment]
Added in c047a76ce45bc09f051055ac160cb1cf6b7b73e4. You should check if the alignment and lineheight, etc. are what you want, they're kinda finicky. I saved each plot as an svg. I couldn't get Oswald Light to work as the font for the label, but Oswald Regular works just fine. We'll also need to run this again after we do the final join with snap/wic as some of the totals will change slightly

**Comment by dgkeyes** [comment]
This looks really good, thanks! We'll likely also need to generate ones for each neighborhood, but that can also wait until we have the final data.

**Comment by dgkeyes** [comment]
I don't think we'll do this for individual neighborhoods so closing this issue
