### ISSUE TITLE
Use icons on map

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#45]
Please use icons in the assets folder. I added both SVG and PNG versions. If possible, please use SVG. 

Please note that the category names have changed slightly. Here is the final list (which I'm also adding in #40 to make sure @grahamammal can get everything in the shape you need it in):

- Corner Stores
- Drug Stores
- International Grocery Stores
- Farmers Markets
- Food Banks/Pantries (merged food banks and food pantries)
- Food Pharmacies
- Free Prepared Food or Hot Meals
- Liquor Stores
- Restaurants
- Restaurants (Fast Food)
- Supermarkets

For the SNAP/WIC stores, I'm going to make different color icons (e.g. red = store that accepts SNAP/WIC). We can add that later.

**Comment by katiejolly** [comment]
Just trying out a small example tonight, so far so good! SVG works great. 
![image](https://user-images.githubusercontent.com/21339677/118229529-fec28680-b440-11eb-80c6-3c674d8fdebc.png)

**Comment by katiejolly** [comment]
Eventually I am hoping to include the icon in the menu names as well

**Comment by dgkeyes** [comment]
Looks good!

**Comment by katiejolly** [comment]
@dgkeyes Looks like there's no farmers market icon in here. Do you have something in mind that you'd like for me to use?

**Comment by dgkeyes** [comment]
Oops, I forgot that one! Just emailed the client to ask for an idea. In the meantime, I chose an icon, which I've added in https://github.com/rfortherestofus/api-food-asset-map/commit/5f232389f7e0882859bcc9b88ea4324e1ef92747. The icon will change, but the file name won't so any code you write should still work when I update the project with the real icon.

**Comment by dgkeyes** [comment]
FYI, I added the correct farmers market icon in ac645764543985dbb26bd19a41e4420de8848c0d so closing this issue
