### ISSUE TITLE
Farmers market icon isn't showing

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#46]
![image](https://user-images.githubusercontent.com/13971585/118534196-d0bd9a80-b6fd-11eb-94c9-fe59d529ebc5.png)

Not really sure why. Let me know if you have any ideas, @katiejolly.

**Comment by katiejolly** [comment]
Ah, it was looking for `farmers-markets.svg` with an s, but the file name is just singular. Fixed.
