### ISSUE TITLE
Make sure API population legend matches data

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#47]
In 3883fbf9d10ae651e6b691f05f8500549b116b29 I changed the API population legend back to using colorQuantile() because I think it was too hard to see the distinctions when it used colorNumeric(). However, I'm now seeing that the data shown in the tooltips doesn't match the legend. [Short video to explain](https://share.rfor.us/qGuE2EmZ).

**Comment by katiejolly** [comment]
Yeah, I had switched it to colorNumeric to see if it had the same issue and
forgot to leave a note in the code about it. I think I'll manually bin the
data and assign colors based on that.

**Comment by dgkeyes** [comment]
Sounds good!

**Comment by katiejolly** [comment]
![image](https://user-images.githubusercontent.com/21339677/118599821-fa5ddc80-b764-11eb-87a8-3ee716c263c7.png)

**Comment by katiejolly** [comment]
Closing since the issue is resolved.
