### ISSUE TITLE
Make neighborhood demographics color palette use reds

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#54]
In laying out the rest of the page, I think it's going to look best if we use a red palette for the demographics. Can you do a color palette that goes from light red to dark red as API population increases?

**Comment by katiejolly** [comment]
What do you think of this? 
![image](https://user-images.githubusercontent.com/21339677/118758087-335c8680-b823-11eb-83d3-114e9ea7138f.png)

**Comment by dgkeyes** [comment]
I like it, thanks!
