### ISSUE TITLE
Adjust clustering

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#56]
Can we adjust the clustering so that it stops clustering once you get down to a certain zoom level? I know I've done this in the past, but I can't remember how.

**Comment by katiejolly** [comment]
Yep, looking into this! Also something I've done and don't remember off the top of my head... it's something with the clustering options 🤔

**Comment by katiejolly** [comment]
It is `disableClusteringAtZoom = ...`
Right now I have it set to 15, but feel free to edit that to match what you had in mind! I think 14-16 are good options from what I've seen.

**Comment by dgkeyes** [comment]
Super, thanks! It looks like it makes the map go pretty slow when we add this. I think I'll probably skip it for now.

**Comment by katiejolly** [comment]
Sounds good! And that's good to know.
