### ISSUE TITLE
Make sure category order is alphabetical

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#58]
Need to wait until we have the new category names (see #26), but then we'll have to reorder. 

See international grocery stores.  

![image](https://user-images.githubusercontent.com/13971585/119052615-b7288700-b979-11eb-8f48-64b9fb1a05cf.png)

**Comment by dgkeyes** [comment]
Assigning this to you @katiejolly because you've built most of the actual map.

**Comment by katiejolly** [comment]
Sounds good, working on this now

**Comment by katiejolly** [comment]
Fixed
