### ISSUE TITLE
Make pages for neighborhoods

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#62]

**Comment by dgkeyes** [comment]
I'll work on making the page for each neighborhood. @katiejolly can we make the code to make the main map a function so I can easily reuse it with data filtered for each neighborhood.

**Comment by katiejolly** [comment]
I've rewritten the code to use a function `draw_resource_map(neighborhoods = NULL)`. With the default NULL, it will draw the map for the whole city. For a particular neighborhood or set of neighborhoods, you can call `draw_resource_map("Richmond")` or for multiple neighborhoods `draw_resource_map(c("Richmond, "Sutro Heights", "Lone Mountain"))`

**Comment by dgkeyes** [comment]
Awesome, thanks! I ended up pulling the code into a separate .R file so I could more easily source it for each neighborhood page.

**Comment by dgkeyes** [comment]
Done in https://github.com/rfortherestofus/api-food-asset-map/commit/85fadccacc675cd1bb5abc10893f2585c9bd3f94
