### ISSUE TITLE
Finalize icon colors for food resources

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#64]
Need different colors for those that accept SNAP/WIC and those that don't

**Comment by katiejolly** [comment]
I took a quick look at changing the icon appearance on the map and edited the `icon_url` to match whether or not the place accepts SNAP/WIC. I added a note to the popup as well, just a start.

![image](https://user-images.githubusercontent.com/21339677/119301233-fc1d1980-bc16-11eb-8095-472b21ce0328.png)

**Comment by dgkeyes** [comment]
Ha, I think we worked on this at the same time, though i think I forgot to commit my changes. I've merged everything and included your (Accepts SNAP/WIC) addition (thanks!). I think we're all set here.
