### ISSUE TITLE
When you have only ‘corner stores’ or ‘supermarkets’ selected, nothing shows up. 

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#68]
The title of this issue is what the client wrote me. Any idea why?

**Comment by katiejolly** [comment]
it looks like someone changed the category labels without updating the labels on the toggle list. i'll fix that now!

**Comment by katiejolly** [comment]
alright, this is fixed and I also put a note in about how to edit category labels in the future!

**Comment by katiejolly** [comment]
I'll have you @dgkeyes render the site, though. But the R script for the maps will now render correctly.

**Comment by dgkeyes** [comment]
Sorry, I think this was probably me who messed it up! 🤦
