### ISSUE TITLE
Import data on providers that offer a food bank/pantry

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#9]
https://www.foodpantries.org/ci/ca-san_francisco

**Comment by dgkeyes** [comment]
https://www.sfmfoodbank.org/find-food/

**Comment by dgkeyes** [comment]
I'm having trouble scraping this. See https://github.com/rfortherestofus/api-food-asset-map/commit/04d3c830818bead0749108de1b55b70708f3c467 It isn't returning text on the page, instead returning text like this:

"\r [[ site.name ]] [[ site.address ]] [[ site.city ]] [[ site.zip ]]\r"

**Comment by grahamammal** [comment]
geocoded data from https://www.foodpantries.org/ci/ca-san_francisco in ef9a8632dd37b843a8c1b00c884adee00a74074e

**Comment by grahamammal** [comment]
scraped and geocoded data from https://www.sfmfoodbank.org/find-food/ in ea7f67c221082154c2b0141031406391dbf2c1d2

**Comment by dgkeyes** [comment]
Wow, I'm very impressed! This would have taken me FOREVER ...
